name: Update Packagist

on:
  release:
    types: [created]

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        uses: mnavarrocarter/packagist-update@v1.0
        with:
          username: "datascaled"
          api_token: ${{ secrets.packagist_token }}
          package_name: datascaled/statamic-fathom-stats